/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.3.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as aiTools from "../aiTools";
import type * as categories from "../categories";
import type * as documents from "../documents";
import type * as favorites from "../favorites";
import type * as feedback from "../feedback";
import type * as reviews from "../reviews";
import type * as services from "../services";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  aiTools: typeof aiTools;
  categories: typeof categories;
  documents: typeof documents;
  favorites: typeof favorites;
  feedback: typeof feedback;
  reviews: typeof reviews;
  services: typeof services;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
